src/framework/framework.ts
shift iteration of symbols to dictionary access so that we won't have performance issues if we want to use symbols for something else
=> shift iteration of symbols to dictionary access

index.ts, package.json, src/framework/framework.ts, src/mock/mockMethod.d.ts, src/transformer/descriptor/method/method.ts, src/transformer/descriptor/mock/mockCall.ts, src/transformer/descriptor/mock/mockMarker.ts, src/transformer/descriptor/tsLibs/typescriptLibsTypeAdapter.ts, src/transformer/descriptor/typeParameter/typeParameter.ts, src/transformer/descriptor/typeReference/typeReference.ts
Basically I had an issue when adding a computer property 
``` ts
return {
[Symbol("__mockMarker"]): true
}
``` 
for some reason typescript compiles it to 
```ts
var _a = {}
_a[Symbol("__mockMarker")] = true;
return _a;
```
the _a variable was clashing to the name of the import
Instead I've manually created the object with a unique name __tsAutoMockObjectReturnValue
=> improve assignment of mockMarker to avoid typescript compilation issues

src/transformer/typeValidator/typeValidator.ts, test/framework/functions.test.ts
Removing the function type as reusable type the method is always properly mocked using the mock factory. Before it was creating a mock in the repository for the function type meaning that every function type were reusing the same MockFactory usage. In the jasmine case this means having only one jasmine.createSpy using always the same name.
=> #18 remove function type as reusable type

src/transformer/matcher/matcher.ts
use path.relative to check if two urls are the same to avoid differences between unix and windows path styles
=> fix(core): use path.relative to check if two urls are the same

src/transformer/descriptor/descriptor.ts, src/transformer/descriptor/typeLiteral/typeLiteral.ts, src/transformer/descriptor/typeLiteral/typeLiteralDeclaration.ts, test/transformer/descriptor/this/this.test.ts
This shows that #88 is not relevant, let me know if I'm doing anything wrong here
=> add test to cover case where interface has a "this" property and a type literal

src/transformer/descriptor/class/classDeclaration.ts, src/transformer/descriptor/descriptor.ts, src/transformer/descriptor/interface/interfaceDeclaration.ts, src/transformer/descriptor/typeLiteral/typeLiteral.ts, src/transformer/mockDefiner/mockDefiner.ts, src/transformer/mockFactoryCall/mockFactoryCall.ts, src/transformer/scope/scope.ts, test/transformer/descriptor/this/this.test.ts
Hello, After yesterday intersection feature I've found an interesting bug related to "this" in intersections.
We are currently solving the "this" problem storing the Declaration everytime we find a potential Mock.
The problem with this approach is that Intersection is not supported correctly because they are a combination of Declaration.
To follow the same design I would have to store not just A declaration, but the mock declarations that could be a list.
I've realized that we don't need to store a Declaration, we can just store the mock key and everytime we find "this" we can reuse that key.
Let me know what you think :).
This PR also refactor the typeLiteral to use the same method as InterfaceDeclartion and ClassDeclaration that I've introdocued with Intersection feature.
=> add support for this in intersections

config/karma/karma.config.transformer.playground.build.js, docs/DETAILS.md, docs/NOT_SUPPORTED.md, package.json, src/transformer/descriptor/constructor/constructorType.ts, src/transformer/descriptor/descriptor.ts, test/playground/playground.test.ts, test/transformer/descriptor/constructor/constructorType.test.ts
This PR adds constructor type to the handled types.
Since a function works for most (if not all) cases my solution is to use it:
```ts
interface Test {
recursive: Test;
recursiveConstructor: new () => Test;
}
const mock = createMock<Test>();
```
will generate something like this
```js
Object.defineProperties(__tsAutoMockObjectReturnValue, {
recursive: {
get: function () {
return _srecursive || (_srecursive = import_Repository.ɵRepository.instance.getFactory("create__test__mock_1")([]));
}, set: function (_recursive) {
_srecursive = _recursive;
}, enumerable: true
},
recursiveConstructor: {
get: function () {
return _srecursiveConstructor || (_srecursiveConstructor = function () {
return import_Repository.ɵRepository.instance.getFactory("create__test__mock_1")([]);
});
}, set: function …
```
=> feat(constructorType): Add constructor type descriptor

docs/DETAILS.md, src/transformer/descriptor/descriptor.ts, src/transformer/descriptor/method/functionType.ts, src/transformer/descriptor/properties/properties.ts, test/transformer/descriptor/methods/methods.test.ts
I'm going to treat construct signature in the same way as call signature.
Something doesn't work perfectly but I think it's a non-problem:
```ts
interface Test {
new (): string;
}
```
is an accepted signature but my implementation can handle only constructions of object-like values.
Let me know if this concerns you
=> feat(constructSignature): add construct signature

docs/DETAILS.md, docs/NOT_SUPPORTED.md, src/transformer/descriptor/descriptor.ts, src/transformer/descriptor/helper/helper.ts, src/transformer/descriptor/method/bodyReturnType.ts, src/transformer/descriptor/method/methodDeclaration.ts, src/transformer/descriptor/mock/mockProperties.ts, src/transformer/descriptor/properties/properties.ts, src/transformer/descriptor/typeQuery/enumTypeQuery.ts, src/transformer/descriptor/typeQuery/typeQuery.ts, src/transformer/mockDefiner/mockDefiner.ts, src/transformer/mockDefiner/modules/moduleNameIdentifier.ts, src/transformer/mockFactoryCall/mockFactoryCall.ts, test/playground/enums.ts, test/playground/playground.test.ts, test/transformer/descriptor/literal/literal.test.ts, test/transformer/descriptor/typeQuery/typeQuery.test.ts, test/transformer/descriptor/utils/typeQuery/typeQueryUtils.ts
This will fix #91 
I've changed how an import of a type `true|false` works, before was behaving in the same way as Boolean, now it works like a normal union picking the first value.
I had to recreate the enum mock even if it wouldn't be needed (the enum is a constant) because there is no way to force the import to stay there. The best solution is for `typeof Enum` to just assign the Enum identifier forcing the import to not disappear. We can do that when https://github.com/microsoft/TypeScript/issues/17552 gets resolved.
To be able to reuse the enum mock I had to create a new parallel process for it, ideally that will be deleted (due to the above statement).
I've changed how we store imports... because I didn't like the loop that we had. Now to get the import identifier of a module we …
=>  feat(typeQuery): add support to typeQuery (typeof) to fix #91

package-lock.json, package.json, src/transformer/descriptor/helper/helper.ts, test/frameworkContext/context.ts, test/frameworkContext/contextDeprecated.ts, test/transformer/context.ts, test/transformer/descriptor/import/importEqual.test.ts, test/transformer/descriptor/utils/interfaces/anotherExportEqual.ts, test/transformer/descriptor/utils/interfaces/exportEqual.ts
I've also removed @types/webpack-env types that were conflicting with @types/node
=> add support for export equals 

package-lock.json, src/transformer/descriptor/descriptor.ts, src/transformer/descriptor/parenthesized/parenthesized.ts, src/transformer/descriptor/properties/properties.ts, src/transformer/descriptor/type/type.ts, test/transformer/descriptor/intersection/functions.test.ts, test/transformer/descriptor/intersection/interfaceWithoutProperties.test.ts, test/transformer/descriptor/parenthesized/intersection.test.ts, test/transformer/descriptor/parenthesized/type.test.ts
I've covered another case and removed one casting... yeah!!!!
Let me know if there were any other scenario about intersections and functions!
=> feat(intersectionsfunction): add support for function intersections

src/transformer/descriptor/helper/helper.ts, src/transformer/descriptor/mock/mockProperties.ts, src/transformer/descriptor/mock/mockProperty.ts, src/transformer/descriptor/mock/propertyLike.ts, src/transformer/descriptor/mock/signatureLike.ts, src/transformer/descriptor/module/module.ts, src/transformer/descriptor/properties/properties.ts, src/transformer/descriptor/typeQuery/enumTypeQuery.ts, src/transformer/descriptor/typeQuery/typeQuery.ts, src/transformer/helper/creator.ts, test/transformer/descriptor/typeQuery/typeQuery.test.ts, test/transformer/descriptor/utils/interfaces/exportDefaultDeclaration.ts, test/transformer/descriptor/utils/interfaces/exportEqualObject.ts
This PR adds support to cases like this:
```ts
import * as STAR from './module1';
import REQUIRE = require('./module2');
const module1Mock: typeof STAR = createMock<typeof STAR>();
const module2Mock: typeof REQUIRE = createMock<typeof REQUIRE>();
```
It takes in account **multiple exports**, **export default** (with ad hoc code) and **export equals**.
I've also:
- added some types to make more clear what is happening with properties and signatures removing the confusion that we had before where everything was casted to a different type every few lines
- added a method to get the alias of a symbol safely (if you call the typescript method with a non-alias symbol it will fail)
- fixed a case where creating a mock of a `typeof Enum` was breaking the original Enum
- fixed the mock of `typeof …
=> feat(typeQuery): add support for typeof of an imported module

definitelyTypedTests/index.js
This is to prevent errors of type:
`Type 'string' does not satisfy the constraint 'object'.`
=> fix(definitelyTyped): use ts-ignore before createMock so that value type modules don't fail

definitelyTypedTests/index.js
Currently types like `gen-readlines` fails with the message:
```
error TS2591: Cannot find name 'Buffer'.
Do you need to install type definitions for node?
Try `npm i @types/node` and then add `node` to the types field in your tsconfig.
```
With this PR I'm adding 'node' in the list of types to fix it.
=> fix(definitelyTyped): add node types in generated tsconfig

.github/workflows/definitelyTyped.yml, .github/workflows/performance.yml
This PR makes sure that when create-pull-request action package makes a new version (keeping the major version 2) we use it without having to update the yml files.
=> build(create-pull-request): make sure we're more lenient with versions of create-pull-request

src/transformer/descriptor/mock/mockPropertiesAssignments.ts, test/transformer/create-mock-values.test.ts, test/transformer/descriptor/properties/assignFalsy.test.ts
With this PR the complex property getters will be changed from
```ts
get prop() {
return m["prop"] || m["prop"] = createMock("some_token");
}
```
to
```ts
get prop() {
return m.hasOwnProperty("prop") ? m["prop"] : m["prop"] = createMock("some_token");
}
```
In this way even by assigning a `null` value it won't create the mock.
This will close #207
=> fix(mockProperty): make sure a falsy value can be assigned to a mock property

config/modules/transformer/tsconfig.json, config/modules/transformer/webpack.js, src/transformer/index.ts, src/transformer/transformer.ts
I've added the export of d ts file for the transformer.
Note: 
I've also moved the default export in a different file, so if we have to swap in the future to a different transformer will be easier. I've tested it locally with jasmine-ts-auto-mock and it works.
Downside of this:
We are exporting plenty of d.ts files because when you set declaration true it will resolve all of the d.ts for the transformer (array, descriptor etc, etc). (Not sure yet if its worth limit it to the public interface and how)
=> fix(transformer): export definitely typed for transformer so it will be easier to read the documentation while developing

src/transformer/descriptor/tsLibs/typecriptLibs.ts, src/transformer/descriptor/tsLibs/typescriptLibsTypes.ts, test/transformer/descriptor/tsLibs/tsLibs.test.ts
This PR enables the use of Date for properties of mocked objects. It will simply instantiate a new instance of Date whenever the surrounding object is defined.
=> enhancement(transformer): Instantiate Date if mocked

package.json, src/transformer/descriptor/enum/enumDeclaration.ts, test/features/random/enum.test.ts, test/playground/jasmine.build.json, test/transformer/descriptor/enum.test.ts
- Fixed case of constant enum computed member:
```ts
enum Constant {
Value = 1 + 2
}
```
- added back npm script to run tests on the built version of playground, this will enable debugging the emitted code
Unfortunately non-constant enum computed members are still not fixed, to do that we have to find once and for all a way to import the enum in the file of the mock and use that directly.
Example of non-constant enum computed member:
```ts
function nonConstant(): number {
return Math.Random();
}
enum Computed {
Value = nonConstant()
}
```
=> fix(enum): fix enum constant computed properties

definitelyTypedTests/src/processRunner.js, src/transformer/descriptor/method/functionType.ts, test/transformer/descriptor/methods/methods.test.ts, ui/src/views/config.mdx, ui/src/views/installation.mdx
Also updated documentation to clarify where to add the transformer options and updated how we generate tsconfig for definitely typed test to reduce errors.
=> fix(transformer): fix interface call signature with undeclared return type

src/transformer/mergeExpression/mergeExpression.ts, src/transformer/mock/mock.ts, src/transformer/mockIdentifier/mockIdentifier.ts, test/frameworkContext/create-mock-list-values.test.ts, test/frameworkContext/create-mock-list.test.ts, test/frameworkContext/utils/function.test.ts
Count the number of create mock list on runtime instead of relying on a numeric literal
I've also added a test to cover the merge default scenario
Simple scenario
```ts
interface A {
a: string;
}
const getNumber: () => number = () => 2;
const type: A[] = createMockList<A>(getNumber());
```
generated code 
```js
var type = (function() {
var s = [];
for (var k = 0; k < getNumber(); k++) {
s.push(ɵRepository.ɵRepository.instance.getFactory('@A_1')([]));
}
return s;
})();
```
With default values
```ts
interface A {
a: string;
}
const type: A[] = createMockList<A>(getNumber(), (index: number) => ({
a: index.toString()
}));
```
generated code
```js
var type = (function() {
var s = [];
for (var k = 0; k < getNumber(); k++) {
s.push(ɵMerge.ɵMerge.mergeIterator(ɵRepository.ɵRepository.instance.getF …
```
=> fix(createMockList): number of mocks on runtime

src/register-mock.ts, src/transformer/mockDefiner/mockDefiner.ts, test/registerMock/generics/generics.test.ts
To solve #604 now situations like Opaque type can be solved with this feature.
Example:
```ts
type Opaque<K, T> = T & { type: K };
registerMock<Opaque<unknown, unknown>>(
(_type: unknown, valueMocked: unknown) => valueMocked as Opaque<unknown, unknown>
);
var mock = createMock<Opaque<'Test', string>>();
expect(mock).toBe('');
var mock2 = createMock<Opaque<'Test2', number>>();
expect(mock2).toBe(0);
```
=> feat(registerMock): allow use of mocked generics parameters in register mock factory

definitelyTypedTests/package-lock.json, definitelyTypedTests/package.json, package-lock.json, package.json, src/extension/method/function.ts
BREAKING CHANGE: typescript >= 4.0.2 is required to use ts-auto-mock
Update your typescript dependency to version >= 4.0.2
=> chore(typescript): update to typescript 4

config/utils/devtool.js, src/transformer/descriptor/typeReference/typeReference.ts, src/transformer/logger/transformerLogger.ts, test/logs/missingTypeDefinition/missingTypeDefinition.warning.test.ts, test/logs/missingTypeDefinition/missingTypeDefinition.warning.type.ts
Thank you for your contribution to ts auto mock repo. 
Before submitting this PR, please make sure:
Prevent failure when a type cannot be located. This can happen if the developer put a ts-ignore when importing from JS libraries with no typings defined.
Also fixed webpack configuration to be able to build in debug mode.
=> fix(typeReference): log warning when type definition does not exists and cannot be located

definitelyTypedTests/src/transformer/customFunctions/create-definitely-typed-mock.ts, definitelyTypedTests/src/transformer/transformer.ts, src/transformer/base/base.ts, src/transformer/customFunctions/create-hydrated-mock.ts, src/transformer/customFunctions/create-mock-list.ts, src/transformer/customFunctions/create-mock.ts, src/transformer/customFunctions/helpers/assert-type-argument-presence.ts, src/transformer/customFunctions/helpers/custom-function-with-type-argument.ts, src/transformer/customFunctions/register-mock.ts, src/transformer/descriptor/helper/helper.ts, src/transformer/matcher/matcher.ts, src/transformer/mock/mock.ts, src/transformer/transformer.ts, tsconfig.base.json
Moved responsibility to identify options to the custom functions, option interface used to change the created mock, this way it's easier to create new custom functions with different mix of options (for example the missing hydrated-list).
This is also a prerequisite for the builder feature and the depth limit feature
=> refactor(transformer): make creation of mock configurable and shift responsibility to custom functions to identify configuration

package-lock.json, package.json, test/createHydratedMock/create-hydrated-mock.test.ts, test/transformer/descriptor/assignments/assignments.test.ts, test/transformer/descriptor/classes.test.ts, test/transformer/descriptor/dictionary.test.ts, test/transformer/descriptor/extends.test.ts, test/transformer/descriptor/functions/functionsWithoutTypes.test.ts, test/transformer/descriptor/generic/generic.test.ts, test/transformer/descriptor/interface.test.ts, test/transformer/descriptor/intersection/intersection.test.ts, test/transformer/descriptor/keyin/keyin.test.ts, test/transformer/descriptor/literal/literal.test.ts, test/transformer/descriptor/tsLibs/tsLibs.test.ts, test/transformer/descriptor/typeQuery/typeQuery.test.ts, test/transformer/utilities/getObjectKeyValues.ts
object equality now uses getOwnPropertyNames to find the keys of the mock. the deep comparison in jasmine version 3 was not considering symbols that are instead included in version 4
https://github.com/jasmine/jasmine/commit/8774562213f371f56a079523678c5141f03b47ec#diff-46cdc2a30e1879f73f5a62a709840911600e79ff44702785f1fafb4234789c57R5183
=> build(dependencies): upgrade to jasmine version 4

package-lock.json, package.json, src/transformer/descriptor/enum/enumDeclaration.ts, src/transformer/descriptor/literal/literal.ts, src/typescriptFactory/typescriptFactory.ts, test/transformer/descriptor/enum.test.ts, test/transformer/descriptor/literal/literal.test.ts, test/transformer/descriptor/utils/types/typeUnion.ts
=> fix(negativeNumbers): convert negative literal numbers to unary expression with minus token
